server:
  port: 8080
spring:
  profiles:
    include: secret
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./testDB;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  ai:
    openai:
      chat:
        enabled: true
        model: gpt-3.5-turbo

  jwt:
    expiration: 86400000